### ISSUE TITLE
update Tencent (CN) potential domains to blocklist.

### ISSUE THREAD

**Issue by lottery248** [duckduckgo/tracker-radar#70]
since i didn't see any trackers that goes to CN servers, I hope DuckDuckGo will update the tracker radar with this company, which is Chinese government-owned.
current path: entities/Tencent Holdings Ltd..json

reference list of links:
https://host.io/tencent.com

edit, there are certain numbers of companies directly owned by Tencent, such as Hypixel Studios. ( www.hytale.com )

**Comment by kdzwinel** [comment]
Thanks for letting us know! We should definitely add tencent.com to the entities/Tencent Holdings Ltd..json entry, but we haven't seen tencent.com being used as a third party in our crawls (maybe because we don't currently crawl from China?). Two domains that we have seen, that seem to be tencent's, are:
- https://slayterdev.github.io/tracker-radar-wiki/domains/tencent-cloud.com.html
- https://slayterdev.github.io/tracker-radar-wiki/domains/tencent-cloud.net.html

**Comment by lottery248** [comment]
due to the fact that China is notorious in big data to surveil its people, I believe they are doing the same overseas.
host.io/tencent.com (which i have mentioned in the op) has mentioned that the company owns more than 27k backlinks. if possible, i would wish to request adding them all and see if it would hint anything.

this is potentially a major exposure, so i also suggest adding crawl from China as well.

**Comment by dharb** [comment]
@lottery248 unfortunately backlinks don't necessarily indicate ownership. For example, there are 6262 backlinks for duckduckgo.com on host.io, but the vast majority aren't owned by DuckDuckGo.

If you have a method to find more domains that Tencent definitely owns but we don't have in our [entity data](https://github.com/duckduckgo/tracker-radar/blob/main/entities/Tencent%20Holdings%20Ltd..json) now, I welcome the contribution. You can either contribute directly by opening a PR or you can add them to this issue and I'll take a look. Just as a heads up, presence of a domain in an entity file does not imply it's a tracker that needs to be blocked.
